[project]
name = "knigoman_app"
version = "1.0.0"
description = "Knigoman Warehouse App"
requires-python = ">=3.10"
dependencies = [
    "flet",
    "flet-audio",
    "flet-audio-recorder",
    "requests",
    "beautifulsoup4",
    "dropbox",
    "google-generativeai",
    "gtts"
]

# Команда для Android разрешить микрофон
[tool.flet.android.permission]
"android.permission.RECORD_AUDIO" = true
