name: Build Flet APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
              
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          update-environment: true

      - name: Install Flet
        run: pip install flet
      
      - name: Build APK
        # Флаг --clear-cache удалит старые хвосты и заставит Flet прочитать новый pyproject.toml
        run: printf 'y\n' | flet build apk --module-name main --clear-cache
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: '**/*.apk'
