name: Build Flet APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
              
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        # Добавлены все необходимые библиотеки для работы ИИ, аудио и Dropbox
        run: pip install flet flet-audio flet-audio-recorder requests beautifulsoup4 dropbox google-generativeai gtts
      
      - - name: Build APK
        run: printf 'y\n' | flet build apk --module-name main --android-permissions android.permission.RECORD_AUDIO=true
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: '**/*.apk'
